CLASS=Presentations

PICS= thicklines.gif thinlines.gif

EXTRAPICS=	big-sigils-plain.gif big-sigils.gif bigmed-sigils.gif \
	small-sigils.gif small-sigils-black.gif \
	caught-short.jpg conway-tooth.jpg cake2.jpg microphone.gif \
	snowstorm.jpg dna.gif carrots.jpg autoload.jpg \
	happy-baby.JPG accordion.jpg Randal.jpg earhart.jpg \
	kurt.jpg placido.jpg smallchange.jpg security-mjd.jpg \
	comma.gif eyeball.jpg a-ko.gif sleepy.jpg present.gif \
	bullshit.jpg bullshit-sm.jpg sen.jpg boss.gif mjd.jpg



EXTRAFILES= 	sigils.html notes.html \
	xml1.html xml2.html xml3.html xml4.html xml5.html styles.css

DISTFILES=

include ../Makefile





