CLASS=Typing

PICS= 

EXTRAPICS= small-sigils.gif bigmed-sigils.gif \
	big-sigils-plain.gif big-sigils.gif \
	eels2.jpg

DISTFILES=

SOURCEFILES= 

SOURCELISTINGS= 

EXTRAFILES= $(SOURCEFILES) $(SOURCELISTINGS) \
	sigils.html

include ../Makefile





